char *_strcat(char *dest, char *f);
char *_strncat(char *f, char *j, int oi);
char*_strncpy(char *de, char *s, int n);
int _strcmp(char*, char*);
void reverse_array(int *, int);
char *string_toupper(char *);
int is_in(char *, char);
char *cap_string(char *);
char *leet(char *);
char *rot13(char *);
void print_number(int);
int _putchar(char c);
char *infinite_add(char *, char*, char*, int);
