#!/bin/bash
touch _putchar.c _islower.c _isalpha.c _abs.c _isupper.c _isdigit.c _strlen.c _puts.c _strcpy.c _atoi.c _strcat.c _strncat.c _strncpy.c _strcmp.c _memset.c _memcpy.c _strchr.c _strspn.c _strpbrk.c _strstr.c
; touch 0-supper.c 0-memset.c 0-strcat.c 1-isdigit.c 1-memcpy.c 1-strncat.c 100-atoi.c ; touch 2-strchr.c 2-strlen.c 2-strncpy.c 3-islower.c 3-puts.c 3-strcmp.c 3-strspn.c ; touch 4-isalpha.c 4strpbrk.c 5-strstr.c ; touch 6-abs.c 9-strcpy.c _putchar.c     
